---

# ---------------------------------------------------------------------------- #
#
# Officially supported permutations by its job name:
#
# - "acceptance-tests-pkg-centos-7"
# - "acceptance-tests-ansible-ubuntu-14-04"
# - "acceptance-tests-ansible-ubuntu-16-04"
#
# Not supported so ignored for now:
#
# - "acceptance-tests-pkg-ubuntu-16-04"
# - "acceptance-tests-pkg-ubuntu-14-04"
# - "acceptance-tests-ansible-centos-7"
#
# ---------------------------------------------------------------------------- #

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:

- name: am-ci
  type: git
  source:
    uri: "https://github.com/artefactual-labs/am-ci"
    branch: main

#- name: slack-notification
#  type: slack-notification
#  source:
#    url: ((slack_webhook))

groups:

- name: fresh-installs
  jobs:
  - start-testing
  - acceptance-tests-pkg-centos-7
  - acceptance-tests-ansible-ubuntu-14-04
  - acceptance-tests-ansible-ubuntu-16-04

- name: upgrades
  jobs:
  - start-testing
  - acceptance-tests-upgrade-pkg-centos-7
  - acceptance-tests-upgrade-ansible-ubuntu-14-04
  - acceptance-tests-upgrade-ansible-ubuntu-16-04

jobs:

- name: start-testing
  plan:
  - get: am-ci
    params:
      submodules: none
      depth: 1

- name: acceptance-tests-pkg-centos-7
  interruptible: true
  serial: true
  plan:
  - get: am-ci
    trigger: true
    passed: [start-testing]
  - task: setup-tugboat
    file: am-ci/acceptance-tests/setup-tugboat.yml
    params:
      ACCESS_TOKEN: ((digitalocean_api.access_token))
      SSH_USER: ((digitalocean_api.ssh_user))
      SSH_KEY: ((digitalocean_api.ssh_key))
      IMAGE: centos-7-x64
  - task: create-droplet
    file: am-ci/acceptance-tests/create-droplet.yml
    params:
      DROPLET_NAME: "archivematica-ci-tests-pkg-centos-7"
    timeout: 5m
  - ensure:
      task: teardown
      file: am-ci/acceptance-tests/teardown-droplet.yml
      params:
        DROPLET_NAME: "archivematica-ci-tests-pkg-centos-7"
      timeout: 5m
    do:
    - task: install-archivematica
      file: am-ci/acceptance-tests/install-archivematica-pkg.yml
      params:
        SCRIPT: am-ci/acceptance-tests/install-archivematica-pkg-centos-7.sh
      timeout: 1h
    - task: install-default-user
      file: am-ci/acceptance-tests/install-default-user.yml
      params:
        SS_URL: "http://127.0.0.1:8001"
        SS_PIPELINE_REMOTE: "http://127.0.0.1:81"
      timeout: 10m
    - task: install-sampledata
      file: am-ci/acceptance-tests/install-sampledata.yml
      timeout: 30m
    - task: run-acceptance-tests
      file: am-ci/acceptance-tests/run-acceptance-tests.yml
      params:
        SELENIUM_HUB_HOST: ((selenium_hub.private))
        SELENIUM_HUB_PORT: ((selenium_hub.port))
        AM_PORT: "81"
        SS_PORT: "8001"
      timeout: 2h
      attempts: 2

- name: acceptance-tests-ansible-ubuntu-16-04
  interruptible: true
  serial: true
  plan:
  - get: am-ci
    trigger: true
    passed: [start-testing]
  - task: setup-tugboat
    file: am-ci/acceptance-tests/setup-tugboat.yml
    params:
      ACCESS_TOKEN: ((digitalocean_api.access_token))
      SSH_USER: ((digitalocean_api.ssh_user))
      SSH_KEY: ((digitalocean_api.ssh_key))
      IMAGE: ubuntu-16-04-x64
  - task: create-droplet
    file: am-ci/acceptance-tests/create-droplet.yml
    params:
      DROPLET_NAME: "archivematica-ci-tests-ansible-ubuntu-16-04"
    timeout: 5m
  - ensure:
      task: teardown
      file: am-ci/acceptance-tests/teardown-droplet.yml
      params:
        DROPLET_NAME: "archivematica-ci-tests-ansible-ubuntu-16-04"
      timeout: 5m
    do:
    - task: install-archivematica
      file: am-ci/acceptance-tests/install-archivematica-ansible-ubuntu.yml
      timeout: 1h
    - task: install-default-user
      file: am-ci/acceptance-tests/install-default-user.yml
      timeout: 10m
    - task: install-sampledata
      file: am-ci/acceptance-tests/install-sampledata.yml
      timeout: 30m
    - task: run-acceptance-tests
      file: am-ci/acceptance-tests/run-acceptance-tests.yml
      params:
        SELENIUM_HUB_HOST: ((selenium_hub.private))
        SELENIUM_HUB_PORT: ((selenium_hub.port))
      timeout: 2h
      attempts: 2

- name: acceptance-tests-ansible-ubuntu-14-04
  interruptible: true
  serial: true
  plan:
  - get: am-ci
    trigger: true
    passed: [start-testing]
  - task: setup-tugboat
    file: am-ci/acceptance-tests/setup-tugboat.yml
    params:
      ACCESS_TOKEN: ((digitalocean_api.access_token))
      SSH_USER: ((digitalocean_api.ssh_user))
      SSH_KEY: ((digitalocean_api.ssh_key))
      IMAGE: ubuntu-14-04-x64
  - task: create-droplet
    file: am-ci/acceptance-tests/create-droplet.yml
    params:
      DROPLET_NAME: "archivematica-ci-tests-ansible-ubuntu-14-04"
    timeout: 5m
  - ensure:
      task: teardown
      file: am-ci/acceptance-tests/teardown-droplet.yml
      params:
        DROPLET_NAME: "archivematica-ci-tests-ansible-ubuntu-14-04"
      timeout: 5m
    do:
    - task: install-archivematica
      file: am-ci/acceptance-tests/install-archivematica-ansible-ubuntu.yml
      timeout: 1h
    - task: install-default-user
      file: am-ci/acceptance-tests/install-default-user.yml
      timeout: 10m
    - task: install-sampledata
      file: am-ci/acceptance-tests/install-sampledata.yml
      timeout: 30m
    - task: run-acceptance-tests
      file: am-ci/acceptance-tests/run-acceptance-tests.yml
      params:
        SELENIUM_HUB_HOST: ((selenium_hub.private))
        SELENIUM_HUB_PORT: ((selenium_hub.port))
      timeout: 2h
      attempts: 2

- name: acceptance-tests-upgrade-pkg-centos-7
  interruptible: true
  serial: true
  plan:
  - get: am-ci
    trigger: true
    passed: [start-testing]
  - task: setup-tugboat
    file: am-ci/acceptance-tests/setup-tugboat.yml
    params:
      ACCESS_TOKEN: ((digitalocean_api.access_token))
      SSH_USER: ((digitalocean_api.ssh_user))
      SSH_KEY: ((digitalocean_api.ssh_key))
      IMAGE: centos-7-x64
      SIZE: s-2vcpu-4gb
  - task: create-droplet-from-snapshot
    file: am-ci/acceptance-tests/create-droplet-from-snapshot.yml
    params:
      DROPLET_NAME: "archivematica-ci-tests-upgrade-pkg-centos-7"
      SNAPSHOT_NAME: "am-1.6.1-centos-7-rpm-with-transfers"
    timeout: 15m
  - ensure:
      task: teardown
      file: am-ci/acceptance-tests/teardown-droplet.yml
      params:
        DROPLET_NAME: "archivematica-ci-tests-upgrade-pkg-centos-7"
      timeout: 5m
    do:
    - task: upgrade-archivematica
      file: am-ci/acceptance-tests/upgrade-archivematica.yml
      timeout: 1h

- name: acceptance-tests-upgrade-ansible-ubuntu-16-04
  interruptible: true
  serial: true
  plan:
  - get: am-ci
    trigger: true
    passed: [start-testing]
  - task: setup-tugboat
    file: am-ci/acceptance-tests/setup-tugboat.yml
    params:
      ACCESS_TOKEN: ((digitalocean_api.access_token))
      SSH_USER: ((digitalocean_api.ssh_user))
      SSH_KEY: ((digitalocean_api.ssh_key))
      IMAGE: ubuntu-16-04-x64
      SIZE: s-2vcpu-4gb
  - task: create-droplet-from-snapshot
    file: am-ci/acceptance-tests/create-droplet-from-snapshot.yml
    params:
      DROPLET_NAME: "archivematica-ci-tests-upgrade-ansible-ubuntu-16-04"
      SNAPSHOT_NAME: "am-1.6.1-ubuntu-xenial-ansible-with-transfers"
    timeout: 15m
  - ensure:
      task: teardown
      file: am-ci/acceptance-tests/teardown-droplet.yml
      params:
        DROPLET_NAME: "archivematica-ci-tests-upgrade-ansible-ubuntu-16-04"
      timeout: 5m
    do:
    - task: upgrade-archivematica
      file: am-ci/acceptance-tests/upgrade-archivematica.yml
      timeout: 1h

- name: acceptance-tests-upgrade-ansible-ubuntu-14-04
  interruptible: true
  serial: true
  plan:
  - get: am-ci
    trigger: true
    passed: [start-testing]
  - task: setup-tugboat
    file: am-ci/acceptance-tests/setup-tugboat.yml
    params:
      ACCESS_TOKEN: ((digitalocean_api.access_token))
      SSH_USER: ((digitalocean_api.ssh_user))
      SSH_KEY: ((digitalocean_api.ssh_key))
      IMAGE: ubuntu-14-04-x64
      SIZE: s-2vcpu-4gb
  - task: create-droplet-from-snapshot
    file: am-ci/acceptance-tests/create-droplet-from-snapshot.yml
    params:
      DROPLET_NAME: "archivematica-ci-tests-upgrade-ansible-ubuntu-14-04"
      SNAPSHOT_NAME: "am-1.6.1-ubuntu-trusty-ansible-with-transfers"
    timeout: 15m
  - ensure:
      task: teardown
      file: am-ci/acceptance-tests/teardown-droplet.yml
      params:
        DROPLET_NAME: "archivematica-ci-tests-upgrade-ansible-ubuntu-14-04"
      timeout: 5m
    do:
    - task: upgrade-archivematica
      file: am-ci/acceptance-tests/upgrade-archivematica.yml
      timeout: 1h
